export const Warrior = [
  //Start of Arms Spec
  {
    id: 1,
    name: "Improved Heroic Strike",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Reduces the cost of your Heroic Strike ability by 1 rage point. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Reduces the cost of your Heroic Strike ability by 2 rage point. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> Reduces the cost of your Heroic Strike ability by 3 rage point. </td> </tr> </table>",
    ],
  },
  {
    id: 2,
    name: "Deflection",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Increases your Parry chance by 1%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Increases your Parry chance by 2%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> ​ Increases your Parry chance by 3%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> ​ Increases your Parry chance by 4%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> ​ Increases your Parry chance by 5%. </td> </tr> </table>",
    ],
  },
  {
    id: 3,
    name: "Improved Rend",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Increases the bleed damage done by your Rend ability by 25%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Increases the bleed damage done by your Rend ability by 50%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> ​ Increases the bleed damage done by your Rend ability by 75%. </td> </tr> </table>",
    ],
  },
  {
    id: 4,
    name: "Improved Charge",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Increases the amount of rage generated by your Charge ability by 3. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> ​ Increases the amount of rage generated by your Charge ability by 6. </td> </tr> </table>",
    ],
  },
  {
    id: 5,
    name: "Iron Will",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Increases your chance to resist stun and charm effects by 3%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Increases your chance to resist stun and charm effects by 6%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> ​ Increases your chance to resist stun and charm effects by 9%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> ​ Increases your chance to resist stun and charm effects by 12%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> ​ Increases your chance to resist stun and charm effects by 15%. </td> </tr> </table>",
    ],
  },
  {
    id: 6,
    name: "Improved Thunder Clap",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​Reduces the cost of your Thunder Clap ability by 1 rage point and increases the damage by 40% and the slowing effect by an additional 4%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​Reduces the cost of your Thunder Clap ability by 2 rage point and increases the damage by 70% and the slowing effect by an additional 7%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> ​Reduces the cost of your Thunder Clap ability by 3 rage point and increases the damage by 100% and the slowing effect by an additional 10%. </td> </tr> </table>",
    ],
  },
  {
    id: 7,
    name: "Improved Overpower",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​Increases the critical strike chance of your Overpower ability by 25%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> ​Increases the critical strike chance of your Overpower ability by 50%. </td> </tr> </table>",
    ],
  },
  {
    id: 8,
    name: "Anger Management",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Generates 1 rage per 3 seconds while in combat. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 1</td></tr> <tr> <td> ​ Generates 1 rage per 3 seconds while in combat. </td> </tr> </table>",
    ],
  },
  {
    id: 9,
    name: "Deep Wounds",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 12 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Your critical strikes cause the opponent to bleed, dealing 40% of your melee weapon's average damage over 12 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> ​ Your critical strikes cause the opponent to bleed, dealing 60% of your melee weapon's average damage over 12 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 10,
    name: "Two-Handed Weapon Specialization",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Increases the damage you deal with two-handed melee weapons by 1%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Increases the damage you deal with two-handed melee weapons by 2%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> ​ Increases the damage you deal with two-handed melee weapons by 3%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> ​ Increases the damage you deal with two-handed melee weapons by 4%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> ​ Increases the damage you deal with two-handed melee weapons by 5%. </td> </tr> </table>",
    ],
  },
  {
    id: 11,
    name: "Impale",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> ​ Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 20%. </td> </tr> </table>",
    ],
  },
  {
    id: 12,
    name: "Poleaxe Specialization",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Increases your chance to get a critical strike with Axes and Polearms by 1%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Increases your chance to get a critical strike with Axes and Polearms by 2%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> ​ Increases your chance to get a critical strike with Axes and Polearms by 3%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> ​ Increases your chance to get a critical strike with Axes and Polearms by 4%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> ​ Increases your chance to get a critical strike with Axes and Polearms by 5%. </td> </tr> </table>",
    ],
  },
  {
    id: 13,
    name: "Death Wish",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ When activated, increases your physical damage by 20% and makes you immune to Fear effects, but increases all damage taken by 5%. Lasts 30 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ When activated, increases your physical damage by 20% and makes you immune to Fear effects, but increases all damage taken by 5%. Lasts 30 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 14,
    name: "Mace Specialization",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Gives your melee attacks a chance to stun your target for 3 sec and generate 7 rage when using a Mace. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Gives your melee attacks a chance to stun your target for 3 sec and generate 7 rage when using a Mace. More effective than Mace Specialization (Rank 1). </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> ​ Gives your melee attacks a chance to stun your target for 3 sec and generate 7 rage when using a Mace. More effective than Mace Specialization (Rank 2). </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> ​ Gives your melee attacks a chance to stun your target for 3 sec and generate 7 rage when using a Mace. More effective than Mace Specialization (Rank 3). </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> ​ Gives your melee attacks a chance to stun your target for 3 sec and generate 7 rage when using a Mace. More effective than Mace Specialization (Rank 4). </td> </tr> </table>",
    ],
  },
  {
    id: 15,
    name: "Sword Specialization",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Gives you a 1% chance to get an extra attack on the same target after dealing damage with your Sword. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Gives you a 2% chance to get an extra attack on the same target after dealing damage with your Sword. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> ​ Gives you a 3% chance to get an extra attack on the same target after dealing damage with your Sword. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> ​ Gives you a 4% chance to get an extra attack on the same target after dealing damage with your Sword. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> ​ Gives you a 5% chance to get an extra attack on the same target after dealing damage with your Sword. </td> </tr> </table>",
    ],
  },
  {
    id: 16,
    name: "Improved Intercept",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Reduces the cooldown of your Intercept ability by 5 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> ​ Reduces the cooldown of your Intercept ability by 10 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 17,
    name: "Improved Hamstring",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Gives your Hamstring ability a 5% chance to immobilize the target for 5 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Gives your Hamstring ability a 10% chance to immobilize the target for 5 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> ​ Gives your Hamstring ability a 15% chance to immobilize the target for 5 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 18,
    name: "Improved Disciplines",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 4 min and increases their duration by 2 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 7 min and increases their duration by 4 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> ​ Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 10 min and increases their duration by 6 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 19,
    name: "Blood Frenzy",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Your Rend and Deep Wounds abilities also increase all melee damage caused to that target by 2%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> ​ Your Rend and Deep Wounds abilities also increase all melee damage caused to that target by 4%. </td> </tr> </table>",
    ],
  },
  {
    id: 20,
    name: "Mortal Strike",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ A vicious strike that deals weapon damage plus 210 and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 1</td></tr> <tr> <td> ​ A vicious strike that deals weapon damage plus 210 and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 21,
    name: "Second Wind",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Whenever you are struck by a Stun or Immobilize effect you will generate 10 rage and 5% of your total health over 10 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> ​ Whenever you are struck by a Stun or Immobilize effect you will generate 20 rage and 10% of your total health over 10 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 22,
    name: "Improved Mortal Strike",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Reduces the cooldown of your Mortal Strike ability by 0.2 sec and increases the damage it causes by 1%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Reduces the cooldown of your Mortal Strike ability by 0.4 sec and increases the damage it causes by 2%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> ​ Reduces the cooldown of your Mortal Strike ability by 0.6 sec and increases the damage it causes by 3%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> ​ Reduces the cooldown of your Mortal Strike ability by 0.8 sec and increases the damage it causes by 4%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> ​ Reduces the cooldown of your Mortal Strike ability by 1 sec and increases the damage it causes by 5%. </td> </tr> </table>",
    ],
  },
  {
    id: 23,
    name: "Endless Rage",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ You generate 25% more rage from damage dealt. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 1</td></tr> <tr> <td> ​ You generate 25% more rage from damage dealt. </td> </tr> </table>",
    ],
  },

  //End of Arms Spec
  //Start of Fury Spec

  {
    id: 24,
    name: "Booming Voice",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Increases the area of effect and duration of your Battle Shout, Demoralizing Shout, and Commanding Shout by 10%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Increases the area of effect and duration of your Battle Shout, Demoralizing Shout, and Commanding Shout by 20%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> ​ Increases the area of effect and duration of your Battle Shout, Demoralizing Shout, and Commanding Shout by 30%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> ​ Increases the area of effect and duration of your Battle Shout, Demoralizing Shout, and Commanding Shout by 40%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> ​ Increases the area of effect and duration of your Battle Shout, Demoralizing Shout, and Commanding Shout by 50%. </td> </tr> </table>",
    ],
  },
  {
    id: 25,
    name: "Cruelty",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Increases your chance to get a critical strike with melee weapons by 1%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Increases your chance to get a critical strike with melee weapons by 2%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> ​ Increases your chance to get a critical strike with melee weapons by 3%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> ​ Increases your chance to get a critical strike with melee weapons by 4%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> ​ Increases your chance to get a critical strike with melee weapons by 5%. </td> </tr> </table>",
    ],
  },
  {
    id: 26,
    name: "Improved Demoralizing Shout",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Increases the melee attack power reduction of your Demoralizing Shout by 8%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Increases the melee attack power reduction of your Demoralizing Shout by 16%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> ​ Increases the melee attack power reduction of your Demoralizing Shout by 24%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> ​ Increases the melee attack power reduction of your Demoralizing Shout by 32%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> ​ Increases the melee attack power reduction of your Demoralizing Shout by 40%. </td> </tr> </table>",
    ],
  },
  {
    id: 27,
    name: "Unbridled Wrath",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Gives you a chance to generate an additional rage point when you deal melee damage with a weapon. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Gives you a chance to generate an additional rage point when you deal melee damage with a weapon. More effective than Unbridled Wrath (Rank 1). </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td>  Gives you a chance to generate an additional rage point when you deal melee damage with a weapon. More effective than Unbridled Wrath (Rank 2). </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td>  Gives you a chance to generate an additional rage point when you deal melee damage with a weapon. More effective than Unbridled Wrath (Rank 3). </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td>  Gives you a chance to generate an additional rage point when you deal melee damage with a weapon. More effective than Unbridled Wrath (Rank 4). </td> </tr> </table>",
    ],
  },
  {
    id: 28,
    name: "Improved Cleave",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Increases the bonus damage done by your Cleave ability by 40%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Increases the bonus damage done by your Cleave ability by 80%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> ​ Increases the bonus damage done by your Cleave ability by 120%. </td> </tr> </table>",
    ],
  },
  {
    id: 29,
    name: "Piercing Howl",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Causes all enemies near the warrior to be dazed, reducing movement speed by 50% for 6 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 1</td></tr> <tr> <td> ​ Causes all enemies near the warrior to be dazed, reducing movement speed by 50% for 6 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 30,
    name: "Blood Craze",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Regenerates 1% of your total health over 6 sec after being the victim of a critical strike. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Regenerates 2% of your total health over 6 sec after being the victim of a critical strike. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> ​ Regenerates 3% of your total health over 6 sec after being the victim of a critical strike. </td> </tr> </table>",
    ],
  },
  {
    id: 31,
    name: "Commanding Presence",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 5%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 10%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> ​ Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 15%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> ​ Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 20%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> ​ Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 25%. </td> </tr> </table>",
    ],
  },
  {
    id: 32,
    name: "Dual Wield Specialization",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Increases the damage done by your offhand weapon by 5%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Increases the damage done by your offhand weapon by 10%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> ​ Increases the damage done by your offhand weapon by 15%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> ​ Increases the damage done by your offhand weapon by 20%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> ​ Increases the damage done by your offhand weapon by 25%. </td> </tr> </table>",
    ],
  },
  {
    id: 33,
    name: "Improved Execute",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Reduces the Rage cost of your Execute ability by 2. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> ​ Reduces the Rage cost of your Execute ability by 4. </td> </tr> </table>",
    ],
  },
  {
    id: 34,
    name: "Enrage",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Gives you a 5% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> ​ Gives you a 10% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> ​ Gives you a 15% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> ​ Gives you a 20% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> ​ Gives you a 25% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike. </td> </tr> </table>",
    ],
  },
  {
    id: 35,
    name: "Improved Slam",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Decreases the casting time of your Slam ability by 0.5 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> ​ Decreases the casting time of your Slam ability by 1 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 36,
    name: "Sweeping Strikes",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Your next 10 melee weapon swings strike an additional nearby opponent. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 1</td></tr> <tr> <td> ​ Your next 10 melee weapon swings strike an additional nearby opponent. </td> </tr> </table>",
    ],
  },
  {
    id: 37,
    name: "Weapon Mastery",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> ​ Reduces the chance for you attacks to be dodged by 1% and reduces the duration of all Disarm effects used against you by 25%. This does not stack with other Disarm duration reducing effects. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> ​ Reduces the chance for you attacks to be dodged by 2% and reduces the duration of all Disarm effects used against you by 50%. This does not stack with other Disarm duration reducing effects. </td> </tr> </table>",
    ],
  },
  {
    id: 38,
    name: "Improved Berserker Rage",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> The Berserker Rage ability will generate 5 rage when used. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> The Berserker Rage ability will generate 10 rage when used. </td> </tr> </table>",
    ],
  },
  {
    id: 39,
    name: "Flurry",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Increases your attack speed by 5% for your next 3 swings after dealing a melee critical strike. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> Increases your attack speed by 15% for your next 3 swings after dealing a melee critical strike. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> Increases your attack speed by 20% for your next 3 swings after dealing a melee critical strike. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> Increases your attack speed by 25% for your next 3 swings after dealing a melee critical strike. </td> </tr> </table>",
    ],
  },
  {
    id: 40,
    name: "Precision",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Increases your chance to hit with melee weapons by 1%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Increases your chance to hit with melee weapons by 2%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> Increases your chance to hit with melee weapons by 3%. </td> </tr> </table>",
    ],
  },
  {
    id: 41,
    name: "Bloodthirst",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Instantly attack the target causing 217 damage. In addition, the next 5 successful melee attacks will restore 80 health. This effect lasts 8 sec. Damage is based on your attack power. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 1</td></tr> <tr> <td> Instantly attack the target causing 217 damage. In addition, the next 5 successful melee attacks will restore 80 health. This effect lasts 8 sec. Damage is based on your attack power. </td> </tr> </table>",
    ],
  },

  {
    id: 42,
    name: "Improved Whirlwind",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Reduces the cooldown of your Whirlwind ability by 1 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> Reduces the cooldown of your Whirlwind ability by 2 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 43,
    name: "Improved Berserker Stance",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Increases attack power by 2% and reduces threat caused by 2% while in Berserker Stance. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Increases attack power by 4% and reduces threat caused by 4% while in Berserker Stance. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> Increases attack power by 6% and reduces threat caused by 6% while in Berserker Stance. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> Increases attack power by 8% and reduces threat caused by 8% while in Berserker Stance. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> Increases attack power by 10% and reduces threat caused by 10% while in Berserker Stance. </td> </tr> </table>",
    ],
  },
  {
    id: 44,
    name: "Rampage",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Warrior goes on a rampage, increasing attack power by 30 and causing most successful melee attacks to increase attack power by an additional 50. This effect will stack up to 5 times. Lasts 30 sec. This ability can only be used after scoring a critical hit. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 1</td></tr> <tr> <td> Warrior goes on a rampage, increasing attack power by 30 and causing most successful melee attacks to increase attack power by an additional 50. This effect will stack up to 5 times. Lasts 30 sec. This ability can only be used after scoring a critical hit. </td> </tr> </table>",
    ],
  },

  //End of Fury Spec
  //Start of Protection Spec

  {
    id: 45,
    name: "Improved Bloodrage",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Increases the instant rage generated by your Bloodrage ability by 3. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> Increases the instant rage generated by your Bloodrage ability by 6. </td> </tr> </table>",
    ],
  },
  {
    id: 46,
    name: "Tactical Mastery",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> You retain up to an additional 5 of your rage points when you change stances. Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> You retain up to an additional 10 of your rage points when you change stances. Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance. More effective than Tactical Mastery (Rank 1). </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> You retain up to an additional 15 of your rage points when you change stances. Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance. More effective than Tactical Mastery (Rank 2). </td> </tr> </table>",
    ],
  },
  {
    id: 47,
    name: "Anticipation",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Increases your Defense skill by 4. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Increases your Defense skill by 8. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> Increases your Defense skill by 12. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> Increases your Defense skill by 16. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> Increases your Defense skill by 20. </td> </tr> </table>",
    ],
  },
  {
    id: 48,
    name: "Shield Specialization",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Increases your chance to block attacks with a shield by 1% and has a 20% chance to generate 1 rage when a block occurs. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Increases your chance to block attacks with a shield by 2% and has a 40% chance to generate 1 rage when a block occurs. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> Increases your chance to block attacks with a shield by 3% and has a 60% chance to generate 1 rage when a block occurs. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> Increases your chance to block attacks with a shield by 4% and has a 80% chance to generate 1 rage when a block occurs. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> Increases your chance to block attacks with a shield by 5% and has a 100% chance to generate 1 rage when a block occurs. </td> </tr> </table>",
    ],
  },
  {
    id: 49,
    name: "Toughness",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Increases your armor value from items by 2%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Increases your armor value from items by 4%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> Increases your armor value from items by 6%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> Increases your armor value from items by 8%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> Increases your armor value from items by 10%. </td> </tr> </table>",
    ],
  },
  {
    id: 50,
    name: "Last Stand",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> When activated, this ability temporarily grants you 30% of your maximum hit points for 20 sec. After the effect expires, the hit points are lost. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 1</td></tr> <tr> <td> When activated, this ability temporarily grants you 30% of your maximum hit points for 20 sec. After the effect expires, the hit points are lost. </td> </tr> </table>",
    ],
  },
  {
    id: 51,
    name: "Improved Shield Block",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Allows your Shield Block ability to block an additional attack, and increases the duration by 1 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 1</td></tr> <tr> <td> Allows your Shield Block ability to block an additional attack, and increases the duration by 1 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 52,
    name: "Improved Revenge",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Gives your Revenge ability a 15% chance to stun the target for 3 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Gives your Revenge ability a 30% chance to stun the target for 3 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> Gives your Revenge ability a 45% chance to stun the target for 3 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 53,
    name: "Defiance",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Increases the threat generated by your attacks by 5% while in Defensive Stance and increases your expertise by 2. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Increases the threat generated by your attacks by 10% while in Defensive Stance and increases your expertise by 4. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> Increases the threat generated by your attacks by 15% while in Defensive Stance and increases your expertise by 6. </td> </tr> </table>",
    ],
  },
  {
    id: 54,
    name: "Improved Sunder Armor",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Reduces the cost of your Sunder Armor and Devastate abilities by 1 rage point. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Reduces the cost of your Sunder Armor and Devastate abilities by 2 rage point. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> Reduces the cost of your Sunder Armor and Devastate abilities by 3 rage point. </td> </tr> </table>",
    ],
  },
  {
    id: 55,
    name: "Improved Disarm",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Increases the duration of your Disarm ability by 1 secs. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Increases the duration of your Disarm ability by 2 secs. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> Increases the duration of your Disarm ability by 3 secs. </td> </tr> </table>",
    ],
  },
  {
    id: 56,
    name: "Improved Taunt",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Reduces the cooldown of your Taunt ability by 1 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> Reduces the cooldown of your Taunt ability by 2 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 57,
    name: "Improved Shield Wall",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Increases the effect duration of your Shield Wall ability by 3 secs. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> Increases the effect duration of your Shield Wall ability by 5 secs. </td> </tr> </table>",
    ],
  },
  {
    id: 58,
    name: "Concussion Blow",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Stuns the opponent for 5 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 1</td></tr> <tr> <td> Stuns the opponent for 5 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 59,
    name: "Improved Shield Bash",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Gives your Shield Bash ability a 50% chance to silence the target for 3 sec. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 2</td></tr> <tr> <td> Gives your Shield Bash ability a 100% chance to silence the target for 3 sec. </td> </tr> </table>",
    ],
  },
  {
    id: 60,
    name: "Shield Mastery",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Increases the amount of damage absorbed by your shield by 10%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Increases the amount of damage absorbed by your shield by 20%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> Increases the amount of damage absorbed by your shield by 30%. </td> </tr> </table>",
    ],
  },
  {
    id: 61,
    name: "One-Handed Weapon Specialization",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Increases the damage you deal with One-Handed Melee weapons by 2%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Increases the damage you deal with One-Handed Melee weapons by 4%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 3</td></tr> <tr> <td> Increases the damage you deal with One-Handed Melee weapons by 6%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 4</td></tr> <tr> <td> Increases the damage you deal with One-Handed Melee weapons by 8%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 5</td></tr> <tr> <td> Increases the damage you deal with One-Handed Melee weapons by 10%. </td> </tr> </table>",
    ],
  },
  {
    id: 62,
    name: "Improved Defensive Stance",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Reduces all spell damage taken while in Defensive Stance by 2%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Reduces all spell damage taken while in Defensive Stance by 4%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> Reduces all spell damage taken while in Defensive Stance by 6%. </td> </tr> </table>",
    ],
  },
  {
    id: 63,
    name: "Shield Slam",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Slam the target with your shield, causing 420 to 440 damage, modified by your shield block value, and dispels 1 magic effect on the target. Also causes a high amount of threat. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 1</td></tr> <tr> <td> Slam the target with your shield, causing 420 to 440 damage, modified by your shield block value, and dispels 1 magic effect on the target. Also causes a high amount of threat. </td> </tr> </table>",
    ],
  },
  {
    id: 64,
    name: "Focused Rage",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Reduces the rage cost of your offensive abilities by 10. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 2</td></tr> <tr> <td> Reduces the rage cost of your offensive abilities by 10. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 3</td></tr> <tr> <td> Reduces the rage cost of your offensive abilities by 10. </td> </tr> </table>",
    ],
  },
  {
    id: 65,
    name: "Vitality",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Increases your total Stamina by 1% and your total Strength by 2%. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 1</td></tr> <tr> <td> Increases your total Stamina by 2% and your total Strength by 4%. </td> </tr> </table>",
    ],
  },
  {
    id: 66,
    name: "Devastate",
    toolTip: [
      "<table style='width: 15rem;'> <tr><td style='color:#40BF40;'>Rank 1</td></tr> <tr> <td> Sunder the target's armor causing the Sunder Armor effect. In addition, causes 50% of weapon damage plus 35 for each application of Sunder Armor on the target. The Sunder Armor effect can stack up to 5 times. </td> </tr> </table>",
      "<table style='width: 15rem;'> <tr><td style='color:#ffd100;'>Rank 1</td></tr> <tr> <td> Sunder the target's armor causing the Sunder Armor effect. In addition, causes 50% of weapon damage plus 35 for each application of Sunder Armor on the target. The Sunder Armor effect can stack up to 5 times. </td> </tr> </table>",
    ],
  },
  //End of Protection Spec
];
